import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinxSerialization)
}

val generatedSecretsDir = layout.buildDirectory.dir("generated/source/secrets/commonMain/kotlin")

val generateSecretsTask = tasks.register("generateSecrets") {
    val localPropertiesFile = rootProject.file("local.properties")
    val outputFile = generatedSecretsDir.map { it.file("org/example/project/config/AppConfig.kt") }

    inputs.file(localPropertiesFile).optional()
    outputs.file(outputFile)

    doLast {
        val properties = Properties()
        if (localPropertiesFile.exists()) {
            localPropertiesFile.inputStream().use { properties.load(it) }
        }
        val baseUrl = properties.getProperty("BASE_URL")
            ?: System.getenv("BASE_URL")
            ?: ""
        val secretKey = properties.getProperty("SECRET_KEY")
            ?: System.getenv("SECRET_KEY")
            ?: ""
        val endpointChecker = properties.getProperty("ENDPOINT_CHECKER")
            ?: System.getenv("ENDPOINT_CHECKER")
            ?: ""

        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by Gradle task generateSecrets. Do not modify manually.
            package org.example.project.config

            object AppConfig {
                const val BASE_URL: String = "$baseUrl"
                const val SECRET_KEY: String = "$secretKey"
                const val ENDPOINT_CHECKER: String = "$endpointChecker"
            }
            """.trimIndent()
        )
    }
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }
    
    android {
       namespace = "org.example.project.shared"
       compileSdk = libs.versions.android.compileSdk.get().toInt()
       minSdk = libs.versions.android.minSdk.get().toInt()
    
       compilerOptions {
           jvmTarget = JvmTarget.JVM_11
       }
       androidResources {
           enable = true
       }
       withHostTest {
           isIncludeAndroidResources = true
       }

    }
    
    sourceSets {
        androidMain.dependencies {
            implementation(libs.androidx.documentfile)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.compose.uiTooling)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.androidx.media3.exoplayer)
            implementation(libs.androidx.media3.ui)
            implementation (libs.accompanist.permissions)
        }
        commonMain {
            kotlin.srcDir(generateSecretsTask.map { generatedSecretsDir })
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.ui)
                implementation(libs.compose.components.resources)
                implementation(libs.compose.uiToolingPreview)
                implementation(libs.androidx.lifecycle.viewmodelCompose)
                implementation(libs.androidx.lifecycle.runtimeCompose)
                implementation(libs.navigation.compose)
                implementation(libs.coil.compose)
                implementation(libs.coil.network.ktor3)
                implementation(libs.coil.video)
                implementation(libs.koin.core)
                implementation(libs.koin.compose)
                implementation(libs.koin.compose.viewmodel)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.client.logging)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.androidx.datastore.preferences.core)
                implementation(libs.coil.gif)
                implementation(libs.material.icons.extended)
                implementation(libs.compose.multiplatform.media.player)
            }
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateSecretsTask)
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}